//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coupon()
        {
            this.DetailBills = new HashSet<DetailBill>(); ImageCoupon = "~/Content/images/Error.png";
        }

        public int ID { get; set; }
        [Display(Name = "Mã khuyến mãi")]
        public string IDCoupon { get; set; }
        [Display(Name = "Tên khuyến mãi")]
        public string NameCoupon { get; set; }
        [Display(Name = "Giảm(%)")]
        public Nullable<double> discount { get; set; }
        [Display(Name = "Số lượng")]
        public Nullable<int> Amount { get; set; }
        [Display(Name = "Tình trạng")]
        public Nullable<bool> Status { get; set; }
        [Display(Name = "Hình ảnh")]
        public string ImageCoupon { get; set; }
        [NotMapped]
        public HttpPostedFileBase UploadImage { get; set; }
        [Display(Name = "Ngày kết thúc")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> DateEnd { get; set; }
        [Display(Name = "Nội dung khuyến mãi")]
        public string Detail { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailBill> DetailBills { get; set; }
    }
}
