//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFastFood.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Revenue
    {
        public int ID { get; set; }
        [DataType(DataType.Date)]
        [Display(Name ="Từ ngày")]
        public Nullable<System.DateTime> RevenueDateStart { get; set; }
        [DataType(DataType.Date)]
        [Display(Name ="Đến ngày")]
        public Nullable<System.DateTime> RevenueDateEnd { get; set; }
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C0}")]
        [Display(Name ="Tổng doanh thu")]
        public Nullable<decimal> RevenueMoney { get; set; }
    }
}
